In [48]:
import numpy as np
import random

#A CONTINUACIÓN VAMOS A DEFINIR TODAS LAS PROPIEDADES DEL PROBLEMA
tablero_array = [[0,1],[2,3],[4,5]]
#tablero_array = [[0,1,2],[3,4,5],[6,7,8]]
tablero_array = [[8,7,6],[3,2,5],[0,1,4]] #TABLERO QUE VAMOS A UTILIZAR
tablero = np.array(tablero_array) #AQUÍ LO CONVERTIMOS EN UNA MATRIZ
casillas = len(tablero)*len(tablero[0]) #NÚMERO DE CASILLAS DEL TABLERO
Q = np.zeros((casillas, casillas), dtype = int) #MATRIZ DE ENTRENAMIENTO INICIALIZADA A 0
R = np.full((casillas, casillas), -1) #MATRIZ DE MOVIMIENTOS INICIALIZADA A -1

#DECLARACIÓN DE R, LA MATRIZ DE MOVIMIENTOS POSIBLES. UNA POSICIÓN DE ESTA MATRIZ TENDRÁ EL VALOR 0 CUANDO EXISTA CAMINO
#ENTRE X (STATE) E Y (ACTION). SI UNO DE ESOS CAMINOS VÁLIDOS CONDUCE A LA META, EL VALOR PASARÁ A SER 100.
#PARA CAMINOS NO VÁLIDOS (POR NO SER CASILLAS VECINAS), EL VALOR SERÁ -1
#HEMOS CONSIDERADO QUE LA META ES LA ÚNICA CASILLA CON UN CAMINO QUE LA LLEVA DE VUELTA A ELLA MISMA

for casilla in range(casillas): #VAMOS A ITERAR POR TODAS LAS CASILLAS DEL TABLERO
    ubicacion = np.where(tablero==casilla) #ALMACENAMOS LAS COORDENADAS DE LA CASILLA DE LA ITERACIÓN ACTUAL

    for y in range(casillas):
        ubicacion_proxima=np.where(tablero==y) #ALMACENAMOS LAS COORDENADAS DE OTRA CASILLA DEL TABLERO PARA COMPROBAR SU
                                               #CERCANÍA CON LA CASILLA DE LA ITERACIÓN ACTUAL
        #COMPROBACIÓN HORIZONTAL Y VERTICAL
        if(ubicacion[0] == ubicacion_proxima[0]+1 and ubicacion[1] == ubicacion_proxima[1]):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
                
        if(ubicacion[0] == ubicacion_proxima[0] and ubicacion[1] == ubicacion_proxima[1]+1):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
            
        if(ubicacion[0] == ubicacion_proxima[0]-1 and ubicacion[1] == ubicacion_proxima[1]):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
                
        if(ubicacion[0] == ubicacion_proxima[0] and ubicacion[1] == ubicacion_proxima[1]-1):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
                
                
        #COMPROBACIÓN DIAGONAL
        if(ubicacion[0] == ubicacion_proxima[0]+1 and ubicacion[1] == ubicacion_proxima[1]+1):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
                
        if(ubicacion[0] == ubicacion_proxima[0]-1 and ubicacion[1] == ubicacion_proxima[1]-1):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
        
        if(ubicacion[0] == ubicacion_proxima[0]-1 and ubicacion[1] == ubicacion_proxima[1]+1):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
                
        if(ubicacion[0] == ubicacion_proxima[0]+1 and ubicacion[1] == ubicacion_proxima[1]-1):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = 0
            
        #NO HAY ACTIONS HACIA UNO MISMO, EXCEPTO QUE SEAS LA META
        if(casilla==y):
            if(y==goal):
                R[casilla,y] = 100
            else:
                R[casilla,y] = -1
            

print("Matriz:\n", tablero)
print("Número de casillas: ", casillas)
print("\nR (matriz de movimientos):\n", R)
print("\nQ (matriz de aprendizaje):\n", Q)

Matriz:
 [[8 7 6]
 [3 2 5]
 [0 1 4]]
Número de casillas:  9

R (matriz de movimientos):
 [[ -1   0   0   0  -1  -1  -1  -1  -1]
 [  0  -1   0   0   0   0  -1  -1  -1]
 [  0   0  -1   0   0   0 100   0   0]
 [  0   0   0  -1  -1  -1  -1   0   0]
 [ -1   0   0  -1  -1   0  -1  -1  -1]
 [ -1   0   0  -1   0  -1 100   0  -1]
 [ -1  -1   0  -1  -1   0 100   0  -1]
 [ -1  -1   0   0  -1   0 100  -1   0]
 [ -1  -1   0   0  -1  -1  -1   0  -1]]

Q (matriz de aprendizaje):
 [[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [53]:
episodios = 50 #NÚMERO DE ITERACIONES QUE TENDRÁ EL ENTRENAMIENTO
gamma = 0.8 #FACTOR DE APRENDIZAJE
state = random.randint(0,8) #ESTADO ALEATORIO DE INCICIO DEL ENTRENAMIENTO
goal = 6 #META PARA TERMINAR EL ENTRENAMIENTO
print("Estado inicial escogido: ", state)
print("Meta escogida: ", goal)
print("\n")

for x in range(episodios):
    print("Estado actual: ", state)
    actions = np.where(R[state]!=-1)[0] #LISTA DE ACCIONES QUE SON POSIBLES
    print("Posibles acciones: ", actions)
    random_action = random.choice(actions)
    print("Acción escogida al azar: ", random_action) #ESCOJO UNA ACCIÓN ALEATORIAMENTE, LA CUAL SERÁ MI PRÓXIMO ESTADO
    print("Peso en R de esa acción: ", R[state, random_action])
    next_actions = np.where(R[random_action]!=-1)[0] #LISTA DE ACCIONES QUE SON POSIBLES EN EL PRÓXIMO ESTADO
    print("Acciones que serán posibles cuando esté en", random_action, ": ", next_actions)
    
    next_actions_Qvalue = np.ones(len(next_actions), dtype=int)
                                   
    for y in range(len(next_actions)):
        next_actions_Qvalue[y] = Q[random_action, next_actions[y]]
    
    print("Peso en Q para esas futuras acciones: ", next_actions_Qvalue)
    
    Q[state, random_action] = R[state, random_action] + gamma * max(next_actions_Qvalue)
    state=random_action
    print("El rendimiento de este episodio de entrenamiento ha sido: ", (Q.sum()/np.max(Q))*100)
    print("\n")
    if(state==goal):
        print("Hemos alcanzado la meta antes de terminar las iteraciones.")
        break
print(Q)

Estado inicial escogido:  6
Meta escogida:  6


Estado actual:  6
Posibles acciones:  [2 5 6 7]
Acción escogida al azar:  7
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 7 :  [2 3 5 6 8]
Peso en Q para esas futuras acciones:  [ 80   0   0 100  64]
El rendimiento de este episodio de entrenamiento ha sido:  1309.0


Estado actual:  7
Posibles acciones:  [2 3 5 6 8]
Acción escogida al azar:  5
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 5 :  [1 2 4 6 7]
Peso en Q para esas futuras acciones:  [ 51   0   0 100   0]
El rendimiento de este episodio de entrenamiento ha sido:  1389.0


Estado actual:  5
Posibles acciones:  [1 2 4 6 7]
Acción escogida al azar:  2
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 2 :  [0 1 3 4 5 6 7 8]
Peso en Q para esas futuras acciones:  [  0   0   0   0  80 100  64  64]
El rendimiento de este episodio de entrenamiento ha sido:  1469.0


Estado actual:  2
Posibles acciones:  [0 1 3 4 5 6 

In [55]:
state = random.randint(0,8) #ESTADO ALEATORIO DE INCICIO DEL RECORRIDO
goal = 6 #META PARA TERMINAR EL RECORRIDO
contador = 0 #NÚMERO DE MOVIMIENTOS USADOS PARA LLEGAR A LA META

print("El estado incial es: ", state)
print("La meta es: ", goal)

#VAMOS A HACER QUE EL AGENTE RECORRA EL TABLERO Y RECORRA EL MEJOR CAMINO
while state!=goal:
    print("\nEstado actual: ", state)
    actions = np.where(R[state]!=-1)[0] #LISTA DE ACCIONES QUE SON POSIBLES EN ESTE MOMENTO
    print("Posibles acciones: ", actions)

    values = np.ones(len(actions), dtype=int) #PESO QUE TIENEN ESAS ACCIONES EN LA MATRIZ Q            
    for y in range(len(actions)):
        values[y] = Q[state, actions[y]]   
    print("Pesos de esas acciones: ", values) 
    
    posicion_mayor_peso = np.where(values==np.max(values))[0][0] #LA POSICIÓN EN EL ARRAY DONDE ESTÁ LA ACCIÓN DE MAYOR PESO
    print("Posición del mejor movimiento, en base a su peso: ", posicion_mayor_peso)
    best_action = actions[posicion_mayor_peso] #LA MEJOR ACCIÓN POSIBLE
    print("Mejor acción: ", best_action)
    
    state=best_action
    contador = contador + 1

print("Hicieron falta", contador, "movimientos para llegar a la meta.\n")
print(Q)

El estado incial es:  2
La meta es:  6

Estado actual:  2
Posibles acciones:  [0 1 3 4 5 6 7 8]
Pesos de esas acciones:  [  0   0   0   0  80 100  64  64]
Posición del mejor movimiento, en base a su peso:  5
Mejor acción:  6
Hicieron falta 1 movimientos para llegar a la meta.

[[  0  51   0   0   0   0   0   0   0]
 [ 40   0  80   0  51   0   0   0   0]
 [  0   0   0   0   0  80 100  64  64]
 [  0   0   0   0   0   0   0  80   0]
 [  0   0  80   0   0  80   0   0   0]
 [  0  51  80   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0  80   0]
 [  0   0  80   0   0  80 164   0  64]
 [  0   0  80   0   0   0   0  64   0]]
