In [84]:
import numpy as np
import random
def iniciar_tablero(lista_tablero, inic_def, goal_def, iteraciones, gamma_def, n_filas, start):
    #A CONTINUACIÓN VAMOS A DEFINIR TODAS LAS PROPIEDADES DEL PROBLEMA
    tablero_array = [[0,1],[2,3],[4,5]]
    #tablero_array = [[0,1,2],[3,4,5],[6,7,8]]
    tablero_array = lista_tablero #TABLERO QUE VAMOS A UTILIZAR
    tablero = np.array(tablero_array) #AQUÍ LO CONVERTIMOS EN UNA MATRIZ
    casillas = len(tablero)*len(tablero[0]) #NÚMERO DE CASILLAS DEL TABLERO
    goal = int(goal_def) #META PARA TERMINAR EL ENTRENAMIENTO
    Q = np.zeros((casillas, casillas), dtype = int) #MATRIZ DE ENTRENAMIENTO INICIALIZADA A 0
    R = np.full((casillas, casillas), -1) #MATRIZ DE MOVIMIENTOS INICIALIZADA A -1

    #DECLARACIÓN DE R, LA MATRIZ DE MOVIMIENTOS POSIBLES. UNA POSICIÓN DE ESTA MATRIZ TENDRÁ EL VALOR 0 CUANDO EXISTA CAMINO
    #ENTRE X (STATE) E Y (ACTION). SI UNO DE ESOS CAMINOS VÁLIDOS CONDUCE A LA META, EL VALOR PASARÁ A SER 100.
    #PARA CAMINOS NO VÁLIDOS (POR NO SER CASILLAS VECINAS), EL VALOR SERÁ -1
    #HEMOS CONSIDERADO QUE LA META ES LA ÚNICA CASILLA CON UN CAMINO QUE LA LLEVA DE VUELTA A ELLA MISMA

    for casilla in range(casillas): #VAMOS A ITERAR POR TODAS LAS CASILLAS DEL TABLERO
        ubicacion = np.where(tablero==casilla) #ALMACENAMOS LAS COORDENADAS DE LA CASILLA DE LA ITERACIÓN ACTUAL

        for y in range(casillas):
            ubicacion_proxima=np.where(tablero==y) #ALMACENAMOS LAS COORDENADAS DE OTRA CASILLA DEL TABLERO PARA COMPROBAR SU
                                                   #CERCANÍA CON LA CASILLA DE LA ITERACIÓN ACTUAL
            #COMPROBACIÓN HORIZONTAL Y VERTICAL
            if(ubicacion[0] == ubicacion_proxima[0]+1 and ubicacion[1] == ubicacion_proxima[1]):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            if(ubicacion[0] == ubicacion_proxima[0] and ubicacion[1] == ubicacion_proxima[1]+1):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            if(ubicacion[0] == ubicacion_proxima[0]-1 and ubicacion[1] == ubicacion_proxima[1]):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            if(ubicacion[0] == ubicacion_proxima[0] and ubicacion[1] == ubicacion_proxima[1]-1):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0


            #COMPROBACIÓN DIAGONAL
            if(ubicacion[0] == ubicacion_proxima[0]+1 and ubicacion[1] == ubicacion_proxima[1]+1):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            if(ubicacion[0] == ubicacion_proxima[0]-1 and ubicacion[1] == ubicacion_proxima[1]-1):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            if(ubicacion[0] == ubicacion_proxima[0]-1 and ubicacion[1] == ubicacion_proxima[1]+1):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            if(ubicacion[0] == ubicacion_proxima[0]+1 and ubicacion[1] == ubicacion_proxima[1]-1):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = 0

            #NO HAY ACTIONS HACIA UNO MISMO, EXCEPTO QUE SEAS LA META
            if(casilla==y):
                if(y==goal):
                    R[casilla,y] = 100
                else:
                    R[casilla,y] = -1


    print("Matriz:\n", tablero)
    print("Número de casillas: ", casillas)
    print("\nR (matriz de movimientos):\n", R)
    print("\nQ (matriz de aprendizaje):\n", Q)
    print("\n")
    start_program = Button(ventana, text="Entrenar matriz", command=lambda: entrenamiento(inic_def, goal_def, iteraciones, gamma_def, n_filas, start, Q, R))
    start_program.grid(column=0, row=n_filas+11)
    start.append(start_program) #LLAMADA A ENTRENAR

In [85]:
def entrenamiento(inic_def, goal_def, iteraciones, gamma_def, n_filas, start, Q, R):
    episodios = int(iteraciones) #NÚMERO DE ITERACIONES QUE TENDRÁ EL ENTRENAMIENTO
    gamma = float(gamma_def) #FACTOR DE APRENDIZAJE
    state = random.randint(0,8) #ESTADO ALEATORIO DE INCICIO DEL ENTRENAMIENTO
    print("Estado inicial escogido: ", state)
    print("Meta escogida: ", goal)
    print("Gamma: ", gamma)
    print("Episodios: ", episodios)

    for x in range(episodios):
        print("Estado actual: ", state)
        actions = np.where(R[state]!=-1)[0] #LISTA DE ACCIONES QUE SON POSIBLES
        print("Posibles acciones: ", actions)
        random_action = random.choice(actions)
        print("Acción escogida al azar: ", random_action) #ESCOJO UNA ACCIÓN ALEATORIAMENTE, LA CUAL SERÁ MI PRÓXIMO ESTADO
        print("Peso en R de esa acción: ", R[state, random_action])
        next_actions = np.where(R[random_action]!=-1)[0] #LISTA DE ACCIONES QUE SON POSIBLES EN EL PRÓXIMO ESTADO
        print("Acciones que serán posibles cuando esté en", random_action, ": ", next_actions)

        next_actions_Qvalue = np.ones(len(next_actions), dtype=int)

        for y in range(len(next_actions)):
            next_actions_Qvalue[y] = Q[random_action, next_actions[y]]

        print("Peso en Q para esas futuras acciones: ", next_actions_Qvalue)

        Q[state, random_action] = R[state, random_action] + gamma * max(next_actions_Qvalue)
        state=random_action
        print("El rendimiento de este episodio de entrenamiento ha sido: ", (Q.sum()/np.max(Q))*100)
        print("\n")
        if(state==goal):
            print("Hemos alcanzado la meta antes de terminar las iteraciones.")
            break
    print(Q)
    
    finish_program = Button(ventana, text="Recorrer tablero", command=lambda: recorrer_tablero(inic_def, goal_def, Q, R))
    finish_program.grid(column=0, row=n_filas+21)
    start.append(finish_program) #LLAMADA A RECORRER EL TABLERO

In [91]:
def recorrer_tablero(inic_def, goal_def, Q, R):
    state = int(inic_def) #ESTADO DE INCICIO DEL RECORRIDO
    goal = int(goal_def) #META DEL RECORRIDO
    contador = 0 #NÚMERO DE MOVIMIENTOS USADOS PARA LLEGAR A LA META

    print("El estado incial es: ", state)
    print("La meta es: ", goal)

    #VAMOS A HACER QUE EL AGENTE RECORRA EL TABLERO Y RECORRA EL MEJOR CAMINO
    while state!=goal:
        print("\nEstado actual: ", state)
        actions = np.where(R[state]!=-1)[0] #LISTA DE ACCIONES QUE SON POSIBLES EN ESTE MOMENTO
        print("Posibles acciones: ", actions)

        values = np.ones(len(actions), dtype=int) #PESO QUE TIENEN ESAS ACCIONES EN LA MATRIZ Q            
        for y in range(len(actions)):
            values[y] = Q[state, actions[y]]   
        print("Pesos de esas acciones: ", values) 

        posicion_mayor_peso = np.where(values==np.max(values))[0][0] #LA POSICIÓN EN EL ARRAY DONDE ESTÁ LA ACCIÓN DE MAYOR PESO
        print("Posición del mejor movimiento, en base a su peso: ", posicion_mayor_peso)
        best_action = actions[posicion_mayor_peso] #LA MEJOR ACCIÓN POSIBLE
        print("Mejor acción: ", best_action)

        state=best_action
        contador = contador + 1

    print("Hicieron falta", contador, "movimientos para llegar a la meta.\n")

In [95]:
from tkinter import *
from tkinter import messagebox as mb 
from random import sample   
import numpy as np
#Iniciamos la ventana Principal
ventana = Tk()
ventana.title("Aprendizaje por Refuerzo")
ventana.geometry('600x600')
#ventana.configure(background = 'dark turquoise')

#Añadimos las entradas de texto de Nº de Filas y Columnas
filas = Label(ventana,text="Numero de Filas")
entry_fila = Entry(ventana, width=5)
filas.grid(column=0,row=0)
entry_fila.grid(column=1,row=0)

columnas = Label(ventana,text="Numero de Columnas")
entry_columna = Entry(ventana, width=5)
columnas.grid(column=0,row=3)
entry_columna.grid(column=1,row=3)

inic = Label(ventana,text="Posicion de inicio")
entry_inic = Entry(ventana, width=5)
entry_inic.insert(END,0)
inic.grid(column=2,row=0)
entry_inic.grid(column=3,row=0)

fin = Label(ventana,text="Objetivo")
entry_fin = Entry(ventana, width=5)
entry_fin.insert(END,6)
fin.grid(column=2,row=3)
entry_fin.grid(column=3,row=3)

gamma = Label(ventana,text="Valor Gamma")
entry_gamma = Entry(ventana, width=5)
entry_gamma.insert(END,0.5)
gamma.grid(column=4,row=0)
entry_gamma.grid(column=5,row=0)

iteraciones = Label(ventana,text="Numero de Iteraciones")
entry_iteraciones = Entry(ventana, width=5)
entry_iteraciones.insert(END,3)
iteraciones.grid(column=4,row=3)
entry_iteraciones.grid(column=5,row=3)


#Clase Matriz
class Matrix():
    def __init__(self,celdas,pos,valores,start):
        self.celdas=celdas[:]
        self.pos=pos[:]
        self.valores=valores[:]
        
        self.start=start[:]

#m1 instanciacion de matriz vacía
m1 = Matrix([],[],[],[])


def aleatorizar(e,n,valores):
    
    random = sample([x for x in range(0,n)],n)[0]
    while(random in valores):
        random = sample([x for x in range(0,n)],n)[0]
    valores.append(random)
    e.insert(END,random)


def generarMatriz(m1):

#En el caso de que m1 sea una matriz ya iniciada, esta tendrá celdas, valores, y posiciones que hay que eliminar previamente    
    celdas = m1.celdas
    pos = m1.pos
    valores = m1.valores
    start=m1.start

    del m1.pos[:]
    del m1.valores[:]
    for b in start:
        b.destroy()
    for c in celdas:
        c.destroy()

#Una vez eliminados validamos las entradas de nfilas y ncolumnas
    validate_tam(entry_fila.get(),entry_columna.get())
    n_filas=int(entry_fila.get())
    n_columnas= int(entry_columna.get())
    total = n_filas * n_columnas

    # Creamos la tabla de entradas
    for row in range(n_filas):
        for column in range(n_columnas):
            index = (row, column)
            e = Entry(ventana, width=10)
            aleatorizar(e,total,valores)
            e.grid(row=row+10, column=column, stick="nsew")
            celdas.append(e)
            pos.append(index)

            
    m1.celdas= celdas
    m1.pos = pos
    m1.valores= valores
    result = zip(pos,valores)
    result_set = set(result)

    nueva_lista = [valores[i:i+n_columnas] for i in range(0, len(valores), n_columnas)]
    print(nueva_lista)
    
    iniciar_tablero(nueva_lista, entry_inic.get(), entry_fin.get(), entry_iteraciones.get(), entry_gamma.get(), n_filas, start)
    #AQUÍ SE HACE LA MAGIA

def validate_tam(n_filas,n_columnas):
    try:
        f= int(n_filas)
        c= int(n_columnas)
    except ValueError:
        mb.showerror("Error","Debe introducir un valor entero como numero de filas y columnas")
    
    if(int(n_filas) == 0 or (n_columnas) == 0):
        mb.showerror("Error","Ni la fila ni la columna puede ser de tamaño 0")
    
#Creamos la matriz según las entradas
btn = Button(ventana, text="Generar Matriz", command=lambda: generarMatriz(m1))
btn.grid(column=0, row=4)




ventana.mainloop()

[[8, 3, 6], [1, 2, 4], [7, 0, 5]]
Matriz:
 [[8 3 6]
 [1 2 4]
 [7 0 5]]
Número de casillas:  9

R (matriz de movimientos):
 [[ -1   0   0  -1   0   0  -1   0  -1]
 [  0  -1   0   0  -1  -1  -1   0   0]
 [  0   0  -1   0   0   0 100   0   0]
 [ -1   0   0  -1   0  -1 100  -1   0]
 [  0  -1   0   0  -1   0 100  -1  -1]
 [  0  -1   0  -1   0  -1  -1  -1  -1]
 [ -1  -1   0   0   0  -1 100  -1  -1]
 [  0   0   0  -1  -1  -1  -1  -1  -1]
 [ -1   0   0   0  -1  -1  -1  -1  -1]]

Q (matriz de aprendizaje):
 [[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


Estado inicial escogido:  3
Meta escogida:  6
Gamma:  0.5
Episodios:  30
Estado actual:  3
Posibles acciones:  [1 2 4 6 8]
Acción escogida al azar:  8
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 8 :  [1 2 3]
Peso en Q para esas futuras acciones:  [0 0 0]
El rendimiento de este

C:\Users\mitea\anaconda3\lib\site-packages\ipykernel_launcher.py:29: RuntimeWarning: invalid value encountered in long_scalars


Estado inicial escogido:  4
Meta escogida:  6
Gamma:  0.5
Episodios:  30
Estado actual:  4
Posibles acciones:  [0 2 3 5 6]
Acción escogida al azar:  3
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 3 :  [1 2 4 6 8]
Peso en Q para esas futuras acciones:  [0 0 0 0 0]
El rendimiento de este episodio de entrenamiento ha sido:  350.0


Estado actual:  3
Posibles acciones:  [1 2 4 6 8]
Acción escogida al azar:  4
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 4 :  [0 2 3 5 6]
Peso en Q para esas futuras acciones:  [ 0 50  0 25  0]
El rendimiento de este episodio de entrenamiento ha sido:  375.0


Estado actual:  4
Posibles acciones:  [0 2 3 5 6]
Acción escogida al azar:  5
Peso en R de esa acción:  0
Acciones que serán posibles cuando esté en 5 :  [0 2 4]
Peso en Q para esas futuras acciones:  [ 0 50 25]
El rendimiento de este episodio de entrenamiento ha sido:  375.0


Estado actual:  5
Posibles acciones:  [0 2 4]
Acción escogida al azar:  4
P